using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace AngularCrudApI1.Model
{
    public class Product
    {
        /*JsonIgnore this attribute tells the JSON serializer (used by Swagger) to ignore the Prid property during serialization,
         * effectively excluding it from Swagger documentation as well. because Prid is autogenerated*/
        [Key]
        [JsonIgnore]
        public int Prid { get; set; }

        [Required]
        [MaxLength(10,ErrorMessage ="Product name cannot be more than 10 charcter")]
        public string Pname { get; set; }

        [Required(ErrorMessage = "Product code is required")]
        public int Pcode { get; set; }
    }
}
    